[project]
name = "week01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "wang", email = "1311194021@qq.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
week01 = "week01:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
